insert into basic_note(note_name, basic_pos) values ('C', 1);
insert into basic_note(note_name, basic_pos) values ('C#', 2);
insert into basic_note(note_name, basic_pos) values ('D', 3);
insert into basic_note(note_name, basic_pos) values ('D#', 4);
insert into basic_note(note_name, basic_pos) values ('E', 5);
insert into basic_note(note_name, basic_pos) values ('F', 6);
insert into basic_note(note_name, basic_pos) values ('F#', 7);
insert into basic_note(note_name, basic_pos) values ('G', 8);
insert into basic_note(note_name, basic_pos) values ('G#', 9);
insert into basic_note(note_name, basic_pos) values ('A', 10);
insert into basic_note(note_name, basic_pos) values ('A#', 11);
insert into basic_note(note_name, basic_pos) values ('B', 12);
insert into tuning(tuning_name, s1, s2, s3, s4, s5, s6) values('E_STANDARD', 'E', 'B', 'G', 'D', 'A', 'E');